package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"io"
	"net/http"
	"os"
	"path"
	"strings"
	"time"

	"anhgelus.world/paris-mobility/backend/internal"
)

const (
	url   = "https://data.iledefrance-mobilites.fr/api/explore/v2.1/catalog/datasets/referentiel-des-lignes/exports/json"
	cache = "lines.json"
)

var (
	pkg         = "backend"
	target      = "lines.go"
	clean       bool
	cacheFolder = internal.BuildFolder
)

func init() {
	flag.BoolVar(&clean, "clean", clean, "clean build")
	flag.StringVar(&target, "target", target, "sets the target")
	flag.StringVar(&pkg, "package", pkg, "sets the package")
	flag.StringVar(&cacheFolder, "cache-folder", cacheFolder, "sets the cache folder")
}

func main() {
	flag.Parse()
	err := os.Mkdir(cacheFolder, 0o755)
	if err != nil && !os.IsExist(err) {
		panic(err)
	}
	var content []byte
	p := path.Join(cacheFolder, cache)
	if !clean {
		f, err := os.Open(p)
		if err != nil {
			if !os.IsNotExist(err) {
				panic(err)
			}
		} else {
			info, err := f.Stat()
			if err != nil {
				panic(err)
			}
			if info.ModTime().Before(time.Now().Add(7 * 24 * time.Hour)) {
				content, err = io.ReadAll(f)
				if err != nil {
					panic(err)
				}
			}
			f.Close()
		}
	}
	if len(content) == 0 {
		resp, err := http.Get(url)
		if err != nil {
			panic(err)
		}
		content, err = io.ReadAll(resp.Body)
		if err != nil {
			panic(err)
		}
		err = os.WriteFile(p, content, 0o644)
		if err != nil {
			panic(err)
		}
	}
	var lines []internal.Line
	err = json.Unmarshal(content, &lines)
	if err != nil {
		panic(err)
	}
	var args string
	if len(os.Args) > 1 {
		args = strings.Join(os.Args[1:], " ")
	}
	var buf bytes.Buffer
	buf.WriteString("// Code generated by generate_lines ")
	buf.WriteString(args)
	buf.WriteString(`; DO NOT EDIT.

package `)
	buf.WriteString(pkg)
	buf.WriteString(`

import "anhgelus.world/paris-mobility/backend/internal"
`)
	groups := make(map[internal.TransportMode][]*internal.Line)
	for _, line := range lines {
		k := line.Mode
		if line.Submode != nil {
			k += ":" + *line.Submode
		}
		groups[k] = append(groups[k], &line)
		line.Generate(&buf)
	}
	buf.WriteString("var Lines = map[internal.TransportMode][]*internal.Line{\n")
	for mode, lines := range groups {
		buf.WriteRune('"')
		buf.WriteString(string(mode))
		buf.WriteRune('"')
		buf.WriteString(": []*internal.Line{")
		for _, line := range lines {
			buf.WriteString(line.Id)
			buf.WriteRune(',')
		}
		buf.WriteString("},\n")
	}
	buf.WriteRune('}')
	err = os.WriteFile(target, buf.Bytes(), 0o644)
	if err != nil {
		panic(err)
	}
}
